if( GL AND NOT OSX32 AND NOT DEDICATED )
    set(SDL "1")
endif()

if( WIN32 )
	 add_definitions(-DAVI_VIDEO)
endif()

if( GL )
    add_definitions(-DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION)
endif()
if( SDL AND NOT DEDICATED )
    add_definitions(-DUSE_SDL)
    #Use system SDL2 for linux.
    if( LINUXALL OR OSXALL )
        include_directories("/usr/local/include/SDL2")
        include_directories("/usr/include/SDL2")
    else()
        include_directories("${SRCDIR}/thirdparty/SDL2")
    endif()
endif()
